#!/usr/bin/env python3
import requests
from bs4 import BeautifulSoup

session = requests.session()
resp = session.get("http://detectportal.firefox.com")
bs = BeautifulSoup(resp.text, 'lxml')
token = bs.find("input", attrs={"name": "_token"})['value']
ceid = bs.find("input", attrs={"name": "_ceid"})['value']
print("Token:", token, "CEID:", ceid)
print("url:", resp.url)
resp_login = session.post("https://railnet.oebb.at/connecttoweb", data={
    '_token': token,
    '_ceid': ceid,
    'checkit': 'on',
    'form_type': 'registration'
    },
    headers={'referer': resp.url})
print(resp_login)
